Feature/user detail
rmohashi/taqtile-onboard pull request #16
Opened 2018-09-06 22:38 UTC by rmohashi

2018-09-06 23:16 UTC, tibawatanabe approved these changes

2018-09-10 14:31 UTC, tibawatanabe requested changes

2018-09-10 14:31 UTC, tibawatanabe commented on src/containers/ListUsers.js
> +    this.setState({
Tem um jeito melhor: usar o [history](https://reacttraining.com/react-router/web/api/history)

2018-09-10 17:01 UTC, rmohashi commented on src/containers/ListUsers.js
> +    this.setState({
cda5821

2018-09-10 17:09 UTC, tibawatanabe approved these changes

2018-09-10 17:57 UTC, merged